### ISSUE TITLE
Rake task users:make_admin_on_all_courses failure

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3718]
Observed in staging:

```
rails aborted!
NoMethodError: undefined method `check_min_points_condition' for #<UnlockCondition:0x0055ff30b12468>
/usr/local/bundle/gems/activemodel-5.0.0.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
/gradecraft/app/models/unlock_condition.rb:122:in `check_assignment_type_condition'
/gradecraft/app/models/unlock_condition.rb:21:in `is_complete?'
/gradecraft/app/models/concerns/unlockable_condition.rb:70:in `block in unlock_condition_count_met_for'
/gradecraft/app/models/concerns/unlockable_condition.rb:70:in `count'
/gradecraft/app/models/concerns/unlockable_condition.rb:70:in `unlock_condition_count_met_for'
/gradecraft/app/models/concerns/unlockable_condition.rb:15:in `unlock!'
/gradecraft/app/models/course_membership.rb:96:in `block in check_unlockables'
/gradecraft/app/models/course_membership.rb:95:in `each'
/gradecraft/app/models/course_membership.rb:95:in `check_unlockables'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:207:in `call'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `block in call'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `each'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:125:in `save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:44:in `save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319:in `block in save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:318:in `save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:41:in `save'
/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/active_record_5.rb:15:in `block in save'
/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent.rb:589:in `with_database_metric_name'
/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/active_record_5.rb:14:in `save'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:34:in `create'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:150:in `block in create'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:351:in `scoping'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:150:in `create'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:224:in `find_or_create_by'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:6:in `find_or_create_by'
/gradecraft/lib/tasks/users.rake:21:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:59:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:59:in `each'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:59:in `block in find_each'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:121:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:214:in `block in in_batches'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:198:in `loop'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:198:in `in_batches'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:120:in `find_in_batches'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/relation/batches.rb:58:in `find_each'
/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:9:in `find_each'
/gradecraft/lib/tasks/users.rake:20:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => users:make_admin_on_all_courses
```

**Comment by chcholman** [comment]
this is a reflection of an old bug that has been fixed in prod - data has now been cleaned up, and this should be fixed.

**Comment by chcholman** [comment]
If it's observed again the fix is to update all UnlockConditions that have the `condition_state: "Min Points"` to be "Minimum Points Earned" (ah, the perils of string matching)
